source 'https://git.coding.net/oweimeio/HWCategory.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

use_frameworks!

target 'HWCore_Example' do
  pod 'HWCore', :path => '../'

  target 'HWCore_Tests' do
    inherit! :search_paths

    
  end
end
	
